version: '3.8'

services:
  db:
    image: postgres
    container_name: healthconnect-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: healthconnect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: healthconnect-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/healthconnect
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: yourpassword

  frontend:
    build: ./frontend
    container_name: healthconnect-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
